### ISSUE TITLE
Ability to assign multiple project types to a project

### ISSUE THREAD

**Issue by pieroapretto** [codeforkansascity/meep-backend#108]
Currently, a user can only select one project type when creating a new project in the `/forms/projects` endpoint

![image](https://user-images.githubusercontent.com/15767173/75631409-4b150400-5bb8-11ea-9ea5-c76f5ef55232.png)

Our stakeholders would like the ability to assign multiple project types to a new project.

**Comment by chris-french** [comment]
looking at the back-end data, I don't think this is going to be a thing. Closing for now.
