### ISSUE TITLE
CORS error on all GET requests

### ISSUE THREAD

**Issue by pieroapretto** [codeforkansascity/meep-backend#109]
GET requests to the API returns the following error:

`Access to XMLHttpRequest at 'http://www.meepmetroenergy.xyz:18773/<path>' from origin 'http://localhost:8200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by chris-french** [comment]
[Flask CORS](https://flask-cors.readthedocs.io/en/latest/) has been added to the `postgres` branch. Closing.
