### ISSUE TITLE
Review comments branch

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep-backend#14]
I made a branch called comments where I riddled the code base with comments that I hope are descriptive enough to get someone up and running. Could someone take a look at the app, mainly app.py, models.py, and resources.py, and let me know if the comments are helpful in conveying what is going on in the code, and what I can do to improve them in order to make reading the code base a more enjoyable experience?

**Comment by evanharmon1** [comment]
In app.py:
```# for some reason doing this import makes models accessible to create_app
# TODO: see if app can be instantiated without this import
from models import User, Role, Project, ProjectType, Location
```
commenting out the import statement didn't seem to affect anything on my end. Is it causing the app not to run or the endpoints not to work? Maybe it's due to difference in our dev environments?

**Comment by evanharmon1** [comment]
These comments really help a ton. I think it will save contributors some time like you said. I'm refactoring various things and trying to adhere to my general understanding of PEP8/pythonic code. But let me know if you'd rather me not do that.

**Comment by evanharmon1** [comment]
Again, these comments are super helpful. I'll try to keep an eye out for other places for explanatory comments. I'll submit a PR for my comment refactors on that branch, but again, they're mainly small pythonic style type things or typos and if you want to bother implementing those.

**Comment by galbwe** [comment]
Sounds good. I'm not planning on being incredibly strict about adhering to PEP8 standards on this project, but you can go ahead and refactor some stuff if you want to.

**Comment by galbwe** [comment]
> In app.py:
> 
> ```
> # TODO: see if app can be instantiated without this import
> from models import User, Role, Project, ProjectType, Location
> ```
> 
> commenting out the import statement didn't seem to affect anything on my end. Is it causing the app not to run or the endpoints not to work? Maybe it's due to difference in our dev environments?

I actually don't remember why I wrote that comment. Maybe for now let's comment out the import and if something breaks unexpectedly, we have a potential cause.

**Comment by evanharmon1** [comment]
> Sounds good. I'm not planning on being incredibly strict about adhering to PEP8 standards on this project, but you can go ahead and refactor some stuff if you want to.

Gotcha. Just let me know if I'm doing anything annoying with that.
