### ISSUE TITLE
Add geometry columns to models

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep-backend#30]
Use the [GeoAlchemy2 library](https://geoalchemy-2.readthedocs.io/en/latest/) to add geometry columns to the existing models. See [here](https://geoalchemy-2.readthedocs.io/en/latest/orm_tutorial.html) for a geoalchemy tutorial, and [here](https://postgis.net/workshops/postgis-intro/geometries.html) for an overview of geometry datatypes that work with postgis.

**Comment by chris-french** [comment]
hasn't this already been done?
