### ISSUE TITLE
Forms validation

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep-backend#86]

**Comment by TelosMachina** [comment]
I'll get started on this. But if anyone else would like to instead just let me know and I can work on something else.

**Comment by evanharmon1** [comment]
I can get started on this unless anyone else would like to. I can work on something else if so. Just let me know.

**Comment by chris-french** [comment]
Can we close this?

**Comment by chris-french** [comment]
Not part of the current MVP. Closing.
