### ISSUE TITLE
Geocoding function

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep-backend#89]
Write a function that takes an address, city, state, and zip code as strings, calls the google geocoding api, and returns a latitude and a longitude as floats. You may assume that the input parameters adhere to the following specifications:
  - address : string 
  - city : string
  - state : string - 2 character abbreviation for a state name
  - zip : int
You may assume all addresses will be in the midwestern united states.

**Comment by DavidGitThisHub** [comment]
I have code that does this. Although it calls google with an address and then scrapes the coordinates from the json response. They always put the coordinates after the address when you search for one.

**Comment by DavidGitThisHub** [comment]
PS. This works for anywhere in the world including addresses like: "Malualkon, South Sudan" whose coords are: 9.0161619, 27.6258817 You know, for future use...

**Comment by galbwe** [comment]
@DavidGitThisHub that is better than what we currently have, so feel free to open a PR. Have you had any issues with them blocking your ip if you use it too frequently?

**Comment by chris-french** [comment]
@chrisschaaf @krisstee  Do we still need this?

**Comment by chrisschaaf** [comment]
I don't believe we need this at this point. The MVP doesn't account for any backend work on mapping data or areas that we could use this towards. The frontend Google Maps React stuff handles it there.
