### ISSUE TITLE
Zip code model

### ISSUE THREAD

**Issue by galbwe** [codeforkansascity/meep-backend#95]
Make a model with geoalchemy and flask-sqlalchemy in ```models.py``` to represent zip codes. The model should follow the same patterns and conventions as those already defined in this file. Three fields that are required are:

  - ```id``` - integer primary key
  - ```zip_code``` - integer
  - ```geometry``` - polygon representing the zip code boundary.

For an example defining a model with geoalchemy, see the [models.py](https://github.com/codeforkansascity/meep-backend/blob/master/api/src/models.py) file on the branch ```geoalchemy-model```.

**Comment by noraanzawi** [comment]
^ I'd like to take a stab at this. Are we wanting to model only zip codes in Kansas City proper like we discussed yesterday or (1) include all zip code boundaries in the project areas (2) include all zip code boundaries in project states?

**Comment by galbwe** [comment]
We will eventually want all zip codes that projects are defined in, but getting all the zip codes for the KC area would be a good start. The problem of obtaining and entering this data into the database is a separate issue however. The task here is to define a database model, which gives us a way to write python to perform database operations without writing sql. I would suggest checking out the test_models file in the tests folder for examples of how database models written in sqlalchemy are used, or take a look at [the sqlalchemy docs](https://docs.sqlalchemy.org/en/13/orm/tutorial.html#version-check), where there is a pretty decent tutorial.

**Comment by chris-french** [comment]
We can pull in zipcode boundaries from TIGER: https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html
